# Generated by Django 3.2.8 on 2021-10-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20210524_2200'),
        ('social', '0012_auto_20210515_2130'),
    ]

    operations = [
    ]
