# Generated by Django 3.2.8 on 2021-10-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_merge_0011_auto_20210524_2200_0012_auto_20210515_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='social.Image'),
        ),
    ]
